resources:
  - name:      myGitRepo
    type:       GitRepo
    configuration:
        gitProvider: myGithub
        path: stmosher27/jfrog-pipelines-steps-examples
        branches:
          include: main  

pipelines:
  - name: myPipeline
    steps:
      - name: step_1
        type: Bash
        configuration:
          inputResources:
            - name: myGitRepo
        execution:
           onExecute:
             - compare_git --resource myGitRepo --commit-range b0676dce3cdb21cb646e5029a4a8724000b1e476..1611e5ef0a2f0645ebed5da0aa706f43af1971ea --directories-only
