resources:
  - name:      myGitRepo
    type:       GitRepo
    configuration:
        gitProvider: myGithub
        path: stmosher27/jfrog-pipelines-steps-examples
        branches:
          include: main  

pipelines:
  - name: myPipeline
    steps:
      - name: step_1
        type: Bash
        configuration:
          inputResources:
            - name: myGitRepo
        execution:
           onExecute:
             - compare_git --resource myGitRepo --commit-range d8594807c2cae7d79e20a6654d9eed072b8df15d..67b1901c601d5159616b6fd63d4f77c1fb479a23
